output_dir: "~/.ros/zhihui_shequ/captures"
cmd_vel_topic: "/cmd_vel"
camera_topic: "/camera/image_raw"
model_name: "smart_car"
use_model_state_motion: true
settle_time: 0.5
startup_camera_wait: 0.5
capture_camera_wait: 0.5

steps:
  - name: start_delay
    action: wait
    duration: 1.0

  - name: leave_start_area
    action: drive
    linear: 0.45
    angular: 0.0
    duration: 18.0

  - name: face_people_area_1
    action: turn
    linear: 0.0
    angular: 0.72
    duration: 2.18

  - name: approach_people_area_1
    action: drive
    linear: 0.40
    angular: 0.0
    duration: 4.5

  - name: people_area_1
    action: capture
    label: people_a

  - name: go_to_people_area_2
    action: drive
    linear: 0.40
    angular: 0.0
    duration: 4.2

  - name: people_area_2
    action: capture
    label: people_b

  - name: face_plate_lane
    action: turn
    linear: 0.0
    angular: 0.72
    duration: 2.18

  - name: go_to_plate_lane
    action: drive
    linear: 0.45
    angular: 0.0
    duration: 6.5

  - name: face_plate_row
    action: turn
    linear: 0.0
    angular: -0.72
    duration: 2.18

  - name: enter_plate_row
    action: drive
    linear: 0.35
    angular: 0.0
    duration: 12

  - name: face_plate_area
    action: turn
    linear: 0.0
    angular: 0.72
    duration: 2.18

  - name: plate_area
    action: capture
    label: plate

  - name: park_forward
    action: drive
    linear: 0.25
    angular: 0.0
    duration: 9
    
  - name: face_plate_area-2
    action: turn
    linear: 0.0
    angular: 0.72
    duration: 2.18
    
  - name: park_forward-2
    action: drive
    linear: 0.25
    angular: 0.0
    duration: 6

  - name: face_plate_row-2
    action: turn
    linear: 0.0
    angular: -0.72
    duration: 2.18
 
  - name: park_forward-2
    action: drive
    linear: 0.25
    angular: 0.0
    duration: 8.5

  - name: reverse_after_park
    action: drive
    linear: -0.25
    angular: 0.0
    duration: 8.0

  - name: face_plate_row-3
    action: turn
    linear: 0.0
    angular: 0.72
    duration: 2.18

  - name: park_forward-3
    action: drive
    linear: 0.25
    angular: 0.0
    duration: 25.5
 
  - name: face_plate_area-4
    action: turn
    linear: 0.0
    angular: -0.72
    duration: 2.18 
    
  - name: park_forward-3
    action: drive
    linear: 0.25
    angular: 0.0
    duration: 8
        
  - name: finish
    action: wait
    duration: 1.0
